### ISSUE TITLE
Reload button for GraqhiQL

### ISSUE THREAD

**Issue by wmertens** [apollostack/apollo-client-devtools#10]
Whenever I change my graphql API, I need to close devtools and open them again to see the changes reflected in graphiql.

It would be nice to have a button that reloads graphiql.

**Comment by stubailo** [comment]
Does GraphiQL have an API for this? If you have time a PR would be appreciated!

**Comment by wmertens** [comment]
There is no API for it, except by remounting the component with a new key.
The schema gets fetched on mount. Relevant issue is
https://github.com/graphql/graphiql/issues/223

So quick hack to have this now would be using an absolutely positioned
reload button that increments a counter that is used for the key of the
graphiql component.

**Comment by wmertens** [comment]
Err, I just realized that switching to a different tab and then back has
the same effect. Good enough for me!
