### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Jpunt** [apollostack/apollo-client-devtools#15]
I love my devtools in dark mode. I'm not sure if we can figure out wether or not the user has selected dark mode and style the Apollo dev tools accordingly, but it would already be a huge improvement if we set a background color like graphiql does:

![screen shot 2017-01-13 at 10 35 05](https://cloud.githubusercontent.com/assets/190501/21925100/30862dba-d97c-11e6-82db-9034053e3256.png)

So the other panels won't look like this:

![screen shot 2017-01-13 at 10 34 47](https://cloud.githubusercontent.com/assets/190501/21925107/393f076a-d97c-11e6-8984-34d33803144b.png)

**Comment by stubailo** [comment]
Can you test out https://github.com/apollostack/apollo-client-devtools/pull/14 and let me know if it works for you?

**Comment by Jpunt** [comment]
Ah sure! Do you know how to install an extension by github/branch?

**Comment by stubailo** [comment]
Did it work?

**Comment by Jpunt** [comment]
Yes 👍 did leave some notes at #14.

**Comment by daniman** [comment]
Closing this, since I merged #14 and added some additional CSS to make the devtools look pretty nice in dark mode!

**Comment by stubailo** [comment]
Awesome!
