### ISSUE TITLE
GrqaphiQL can't contains multiple queries

### ISSUE THREAD

**Issue by linonetwo** [apollostack/apollo-client-devtools#5]
If there were more than one queries in the graphiql, it will returns:

```json
{
  "errors": [
    {
      "message": "Must provide operation name if query contains multiple operations.",
      "locations": null,
      "path": null
    }
  ]
}

**Comment by stubailo** [comment]
Does GraphiQL normally support this? I feel like this is a limitation of GraphiQL itself, rather than the dev tools.

**Comment by linonetwo** [comment]
GraphiQL surely supports this:
![qq 20161215184224](https://cloud.githubusercontent.com/assets/3746270/21220945/6441a036-c2f6-11e6-90c2-fff54a46c69f.png)

**Comment by linonetwo** [comment]
But this tool is so convenient that I think my days of using multiple queries will pass.

**Comment by stubailo** [comment]
That's just surprising because we're using regular off-the-shelf GraphiQL - I would expect it to support everything GraphiQL does... is the dropdown you're showing coming from the standard `npm install graphiql`?

**Comment by linonetwo** [comment]
No, it's from apollo-server :

```javascript
import express from 'express';
import bodyParser from 'body-parser';
import { apolloExpress, graphiqlExpress } from 'apollo-server';

...

graphQLServer.use('/graphiql', graphiqlExpress({ endpointURL: '/graphql' }));

graphQLServer.listen(GRAPHQL_PORT, () => console.log(
  `GraphQL Server is now running on http://localhost:${GRAPHQL_PORT}/graphiql`
));
```

**Comment by stubailo** [comment]
Yeah, that uses the standard one, so I'm surprised it's different. Maybe the Apollo network interface is doing something weird when the request passes through. @daniman if you have a moment might be something to look at - we should just print the request at each point and see when the `operationName` disappears.

**Comment by daniman** [comment]
@linonetwo this issue should be fixed by the commit I just made! I'll release v1.0.3 of the extension to the chrome web store.

**Comment by linonetwo** [comment]
Nice!
