### ISSUE TITLE
Tools disabled

### ISSUE THREAD

**Issue by tomitrescak** [apollostack/apollo-client-devtools#7]
Hi, I am not sure what I am doing wrong, but tools are always disabled.

I have upgraded apollo-client to (0.5.20) and react-apollo to (0.7.1)
No luck (I also noticed that __APOLLO_CLIENT__ was not in global variables at this point)

Then, I have  added following code to my client initialisation:

```
client = new ApolloClient({
      networkInterface,
      dataIdFromObject: (result: any) => {
        return result._id;
      },
      connectToDevTools: true
    });

    window.__APOLLO_CLIENT__ = client;
```

Still no luck.
Running latest Chrome 55, on Mac OS X.

**Comment by tomitrescak** [comment]
And just like that after several reloads and browser restart all is jolly ...

**Comment by stubailo** [comment]
Yeah it's odd, we'll just have to work on making it more stable over time! One of the things I learned from this project is that the Chrome APIs don't exactly make these things easy. But they do make them possible!
